#!/usr/bin/env bash

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

source "${dir}/includes/source-or-message.bash.inc"

main() {
	local command="${@:1}"
	if [ -z "${command}" ]; then
		echo "USAGE: ${0} <command>"
		exit 1
	fi

	source_or_message \
		"${dir}/project-config.bash.inc" \
		"Configuration does not exist. Copy ${dir}/project-config.bash.inc.template to ${dir}/projct-config.bash.inc and configure it for your project"

	local project="${GCP_PROJECT}"
	local key="${GCLOUD_KEY}"

	./vendor/runtime "gcloud" "./gcloud-scripts/initialize-gcloud.sh ${project} ${key}; gcloud ${command}"
}

main "$@"